[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "src"
version = "0.0.1"
description = "A short description of the project."
authors = [
  { name = "Mohamed" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
dependencies = [
    "black",
    "flake8",
    "hydra-core>=1.3.2",
    "isort",
    "omegaconf>=2.3.0",
    "pandas>=2.0.0",
    "pip",
    "python-dotenv",
    "scikit-learn",
    "numpy",
    "nltk",
    "scipy",
    "bm25s",
    "xgboost",
    "mlflow",
    "gensim",
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",
    "matplotlib",
    "dvc>=3.67.1",
]
requires-python = ">=3.12"

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["src"]
force_sort_within_sections = true


